# Configuration for the script


label_size: Medium            # Size of labels (small/medium/large) #small = xx(j * k) per page, medium = xx(j * k) per page, large = xx(j * k) per page
qr_code: true                 # Enable or disable QR code generation
scale_bar: true               # Enable or disable scale bar
#logo_path:                    # Path to the logo file # if empty no logo is shown.

Project_name: "Project title"
filename: "test"

sequential_labels: true
Prefix: "ABC" #prefix for all specimen numbers, if empty no prefix, if sequential numbers is true
Suffix: "" #suffix for all specimen numbers, if empty no prefix, if sequential numbers is true
Range: 1,10 #specimen number range, if empty no prefix, if sequential numbers is true

Labels_list: ['ABC20', 'ABC30', 'ABC40']
